### ISSUE TITLE
Granting of permissions for new maintainer

### ISSUE THREAD

**Issue by arne48** [ros-gbp/rqt_console-release#1]
Hello,
In the progress of the [Call for maintainers for some RQt packages!](https://discourse.ros.org/t/call-for-maintainers-for-some-rqt-packages/19827) I took over, among others, the maintenance of this package.
I already got granted access to the packages themselves, but to be able to release a new version, I also need access to this package.

As requested by Katherine_Scott on discourse, I hereby would like to state my status as the current maintainer and would like to request permissions for this package to allow me to release new versions.

Thank you very much in advance.

**Comment by arne48** [comment]
I am sorry @nuclearsandwich I now had the opportunity to release a new version for this package.
It seems that my access rights are not sufficient.
_catkin_prepare_release_ worked so I would assume that my keys are setup correctly, however, _bloom-release_ gives me a permission denied error.
I am sorry trouble you again with this topic.

**Comment by nuclearsandwich** [comment]
I've sent a new invitation to collaborate on this repository. Can you please check now?

**Comment by arne48** [comment]
Hello @nuclearsandwich,
thank you very much for giving me access to this release repository.
I quickly tested the write access via the GitHub editor and it appeared successful.
I am sorry but could you please also give me access to the other release repositories of the packages I am maintaining now?

* [https://github.com/ros-gbp/rqt_robot_dashboard-release](https://github.com/ros-gbp/rqt_robot_dashboard-release)
* [https://github.com/ros-gbp/rqt_logger_level-release](https://github.com/ros-gbp/rqt_logger_level-release)
* [https://github.com/ros-gbp/rqt_runtime_monitor-release](https://github.com/ros-gbp/rqt_runtime_monitor-release)

Thank you very much and I am sorry for the inconveniences.

**Comment by nuclearsandwich** [comment]
> could you please also give me access to the other release repositories of the packages I am maintaining now?

No need to apologize, we need to find a maintainable management workflow for release repository succession and right now I guess I'm "it". :P

One thing you could do to help make it easier for me is drop links to the commits for each package that add you as a listed maintainer or any other public artifacts documenting your maintainership of the listed packages.

**Comment by arne48** [comment]
Yes, it seems that the grown permission management via individual collaborators per package is becoming quite a burden to maintain.
Sending you public proof is of course no problem.
Here are the merged changes to the package files :)
* [https://github.com/ros-visualization/rqt_logger_level/pull/10](https://github.com/ros-visualization/rqt_logger_level/pull/10)
* [https://github.com/ros-visualization/rqt_robot_dashboard/pull/10](https://github.com/ros-visualization/rqt_robot_dashboard/pull/10)
* [https://github.com/ros-visualization/rqt_runtime_monitor/pull/7](https://github.com/ros-visualization/rqt_runtime_monitor/pull/7)

Thank you very much.
And if there is anything else in the future I could be helpful with, please let me know :)

**Comment by nuclearsandwich** [comment]
Invitations are dispatched. Once you've accepted and confirmed access please close this issue or comment with any problems you have. Thanks!

**Comment by arne48** [comment]
Thank you very much, everything appears to work now.
